language: python
python:
  - "2.6"
  - "2.7"
install:
   - pip install -r dev_requirements.txt --use-mirrors
   - pip freeze
   - python setup.py develop
env:
  - DJANGO="1.3.3"
  - DJANGO="1.4.1"
  - DJANGO="1.5.1"
script: python setup.py nosetests
services:
  - redis-server
